### PR TITLE
Compare results

### PR DESCRIPTION
**Pull request by awunderground**

### CODE REVIEW

**Comment by lbotti319** [comment]
Any chance you can compile that Rmd to a pdf so I can view it in github?

**Comment by lbotti319** [comment]
How is interval overlap being measured in the `Credible Interval Overlap` section?

**Comment by lbotti319** [comment]
I really like these comparisons overall though. As we get results for MAR and MNAR we will want to swap out some of the MCAR scenarios. This is looking great

**Comment by awunderground** [comment]
> How is interval overlap being measured in the `Credible Interval Overlap` section?

I wrote about this in the outline: 
Screen Shot 2021-05-12 at 1 44 29 PM

**Review by lbotti319 — APPROVED** [review]

**Pull request merged**
