### PR TITLE
Choosing X variables

### PR DESCRIPTION
**Pull request by inespancorbo**

### CODE REVIEW

**Comment by lbotti319** [comment]
Using the label encoder on categorical variables makes me nervous because it introduces ordering to the values that might not actually be there.

**Comment by inespancorbo** [comment]
Feel free to change to one hot or some other scalar transform. But I believe the transform depends on the prior we will be using. For example, if we are going to be using a multinomial I don't think the transformation matters because we are assigning probabilities.

**Comment by lbotti319** [comment]
Will our proposal distribution in the MH algorithm stop being normal depending on the priors?

**Comment by inespancorbo** [comment]
But agree that if we one hot for example, we would get "more features" in a sense and we could use Bernoulli for basically all!

**Comment by inespancorbo** [comment]
Proposal for which parameter/variable? If we are trying to sample from `Sex` for  example, we cannot use a normal I think? The proposal has to have same support as the full conditional we are trying to sample from. Otherwise we could accept 5.89 for example and that's not in the support of `Sex`.

**Comment by lbotti319** [comment]
Beta.
The proposal for the model coefficients is going to be normal regardless of the distribution of the underlying variable, right?

**Comment by inespancorbo** [comment]
I guess. Because we aren't restricting beta to anything? So the support can be (-infinty, infinity) and a normal can be decent to propose from. We are saying $y_i = x_0 + x_{i1}\beta_1 + ... + x_{in}\beta_n$ for n being number of features ... However, $x_0 + x_{i1}\beta_1 + ... + x_{in}\beta_n$ will most likely not be an integer between 0 and 20 (the grades) so this was sort of my question in the notebook. Are we ok with our grades being normally distributed? or should we transform (like the data in Exam 1)?

But don't know, let me know if I'm thinking about this wrong.

**Comment by lbotti319** [comment]
>  Are we ok with our grades being normally distributed?
I'm fine with that.

That seems like a separate question to me than using the LabelEncoder though. It's going to make our beta values unreliable because of the ordering we are introducing by using it.  Additionally it is going to screw with the correlation for similar reasons.

My PR has code for OneHot as well, so you don't need to recode it if you don't want to.

**Pull request merged**
